<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="17" failed="2" ignored="1" total="22" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="144329" started-at="2018-09-23T16:53:37Z" finished-at="2018-09-23T16:56:01Z">
    <groups>
    </groups>
    <test name="TestLASTPPass" duration-ms="74441" started-at="2018-09-23T16:53:37Z" finished-at="2018-09-23T16:54:51Z">
      <class name="Cosmos_Testcases.LATraditionalstppass">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="beforeTest" is-config="true" duration-ms="7074" started-at="2018-09-23T16:53:37Z" finished-at="2018-09-23T16:53:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="selectNBSBranchInward()[pri:1, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="selectNBSBranchInward" duration-ms="47411" started-at="2018-09-23T16:53:44Z" finished-at="2018-09-23T16:54:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectNBSBranchInward -->
        <test-method status="FAIL" signature="submitReciept()[pri:2, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="submitReciept" duration-ms="18983" started-at="2018-09-23T16:54:31Z" depends-on-methods="Cosmos_Testcases.LATraditionalstppass.selectNBSBranchInward" finished-at="2018-09-23T16:54:50Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at pageObjectClasses.ProposalDetails.fillInstrumentDetails(ProposalDetails.java:191)
at Cosmos_Testcases.LATraditionalstppass.submitReciept(LATraditionalstppass.java:98)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitReciept -->
        <test-method status="SKIP" signature="pendingBranchScrutny()[pri:3, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="pendingBranchScrutny" duration-ms="0" started-at="2018-09-23T16:54:50Z" depends-on-methods="Cosmos_Testcases.LATraditionalstppass.submitReciept" finished-at="2018-09-23T16:54:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LATraditionalstppass.pendingBranchScrutny()[pri:3, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LATraditionalstppass.pendingBranchScrutny()[pri:3, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pendingBranchScrutny -->
        <test-method status="SKIP" signature="scanAndIndex()[pri:5, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="scanAndIndex" duration-ms="0" started-at="2018-09-23T16:54:50Z" depends-on-methods="Cosmos_Testcases.LATraditionalstppass.selectDispatch" finished-at="2018-09-23T16:54:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LATraditionalstppass.scanAndIndex()[pri:5, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LATraditionalstppass.scanAndIndex()[pri:5, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- scanAndIndex -->
        <test-method status="SKIP" signature="copsInwardBucket()[pri:6, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="copsInwardBucket" duration-ms="0" started-at="2018-09-23T16:54:50Z" depends-on-methods="Cosmos_Testcases.LATraditionalstppass.scanAndIndex" finished-at="2018-09-23T16:54:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LATraditionalstppass.copsInwardBucket()[pri:6, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LATraditionalstppass.copsInwardBucket()[pri:6, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- copsInwardBucket -->
        <test-method status="SKIP" signature="selectDispatch()[pri:4, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="selectDispatch" duration-ms="0" started-at="2018-09-23T16:54:50Z" depends-on-methods="Cosmos_Testcases.LATraditionalstppass.pendingBranchScrutny" finished-at="2018-09-23T16:54:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LATraditionalstppass.selectDispatch()[pri:4, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LATraditionalstppass.selectDispatch()[pri:4, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectDispatch -->
        <test-method status="SKIP" signature="nbsDataEntry()[pri:7, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="nbsDataEntry" duration-ms="0" started-at="2018-09-23T16:54:50Z" depends-on-methods="Cosmos_Testcases.LATraditionalstppass.copsInwardBucket" finished-at="2018-09-23T16:54:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LATraditionalstppass.nbsDataEntry()[pri:7, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LATraditionalstppass.nbsDataEntry()[pri:7, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nbsDataEntry -->
        <test-method status="SKIP" signature="copsQc()[pri:8, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="copsQc" duration-ms="0" started-at="2018-09-23T16:54:50Z" depends-on-methods="Cosmos_Testcases.LATraditionalstppass.nbsDataEntry" finished-at="2018-09-23T16:54:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LATraditionalstppass.copsQc()[pri:8, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LATraditionalstppass.copsQc()[pri:8, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- copsQc -->
        <test-method status="SKIP" signature="applicationTracker()[pri:9, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="applicationTracker" duration-ms="0" started-at="2018-09-23T16:54:50Z" depends-on-methods="Cosmos_Testcases.LATraditionalstppass.copsQc" finished-at="2018-09-23T16:54:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LATraditionalstppass.applicationTracker()[pri:9, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LATraditionalstppass.applicationTracker()[pri:9, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- applicationTracker -->
        <test-method status="SKIP" signature="proposalEnquiry()[pri:10, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="proposalEnquiry" duration-ms="0" started-at="2018-09-23T16:54:50Z" depends-on-methods="Cosmos_Testcases.LATraditionalstppass.applicationTracker" finished-at="2018-09-23T16:54:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LATraditionalstppass.proposalEnquiry()[pri:10, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LATraditionalstppass.proposalEnquiry()[pri:10, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- proposalEnquiry -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:Cosmos_Testcases.LATraditionalstppass@7d1f3fe9]" name="aftermethod" is-config="true" duration-ms="847" started-at="2018-09-23T16:54:50Z" finished-at="2018-09-23T16:54:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
      </class> <!-- Cosmos_Testcases.LATraditionalstppass -->
    </test> <!-- TestLASTPPass -->
    <test name="TestLATOIL" duration-ms="69672" started-at="2018-09-23T16:54:52Z" finished-at="2018-09-23T16:56:01Z">
      <class name="Cosmos_Testcases.LACosmosToIL">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="beforeTest" is-config="true" duration-ms="5209" started-at="2018-09-23T16:54:52Z" finished-at="2018-09-23T16:54:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="selectNBSBranchInward()[pri:1, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="selectNBSBranchInward" duration-ms="43882" started-at="2018-09-23T16:54:57Z" finished-at="2018-09-23T16:55:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectNBSBranchInward -->
        <test-method status="FAIL" signature="submitReciept()[pri:2, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="submitReciept" duration-ms="19820" started-at="2018-09-23T16:55:41Z" depends-on-methods="Cosmos_Testcases.LACosmosToIL.selectNBSBranchInward" finished-at="2018-09-23T16:56:00Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at pageObjectClasses.ProposalDetails.fillInstrumentDetails(ProposalDetails.java:191)
at Cosmos_Testcases.LACosmosToIL.submitReciept(LACosmosToIL.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitReciept -->
        <test-method status="SKIP" signature="pendingBranchScrutny()[pri:3, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="pendingBranchScrutny" duration-ms="0" started-at="2018-09-23T16:56:00Z" depends-on-methods="Cosmos_Testcases.LACosmosToIL.submitReciept" finished-at="2018-09-23T16:56:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LACosmosToIL.pendingBranchScrutny()[pri:3, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LACosmosToIL.pendingBranchScrutny()[pri:3, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pendingBranchScrutny -->
        <test-method status="SKIP" signature="selectDispatch()[pri:4, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="selectDispatch" duration-ms="0" started-at="2018-09-23T16:56:00Z" depends-on-methods="Cosmos_Testcases.LACosmosToIL.pendingBranchScrutny" finished-at="2018-09-23T16:56:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LACosmosToIL.selectDispatch()[pri:4, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LACosmosToIL.selectDispatch()[pri:4, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectDispatch -->
        <test-method status="SKIP" signature="scanAndIndex()[pri:5, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="scanAndIndex" duration-ms="0" started-at="2018-09-23T16:56:00Z" depends-on-methods="Cosmos_Testcases.LACosmosToIL.selectDispatch" finished-at="2018-09-23T16:56:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LACosmosToIL.scanAndIndex()[pri:5, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LACosmosToIL.scanAndIndex()[pri:5, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- scanAndIndex -->
        <test-method status="SKIP" signature="copsInwardBucket()[pri:6, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="copsInwardBucket" duration-ms="0" started-at="2018-09-23T16:56:00Z" depends-on-methods="Cosmos_Testcases.LACosmosToIL.scanAndIndex" finished-at="2018-09-23T16:56:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LACosmosToIL.copsInwardBucket()[pri:6, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LACosmosToIL.copsInwardBucket()[pri:6, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- copsInwardBucket -->
        <test-method status="SKIP" signature="nbsDataEntry()[pri:7, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="nbsDataEntry" duration-ms="0" started-at="2018-09-23T16:56:00Z" depends-on-methods="Cosmos_Testcases.LACosmosToIL.copsInwardBucket" finished-at="2018-09-23T16:56:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LACosmosToIL.nbsDataEntry()[pri:7, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LACosmosToIL.nbsDataEntry()[pri:7, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nbsDataEntry -->
        <test-method status="SKIP" signature="copsQc()[pri:8, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="copsQc" duration-ms="0" started-at="2018-09-23T16:56:00Z" depends-on-methods="Cosmos_Testcases.LACosmosToIL.nbsDataEntry" finished-at="2018-09-23T16:56:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LACosmosToIL.copsQc()[pri:8, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LACosmosToIL.copsQc()[pri:8, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- copsQc -->
        <test-method status="SKIP" signature="UWBucket()[pri:10, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="UWBucket" duration-ms="0" started-at="2018-09-23T16:56:00Z" depends-on-methods="Cosmos_Testcases.LACosmosToIL.copsQc" finished-at="2018-09-23T16:56:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LACosmosToIL.UWBucket()[pri:10, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LACosmosToIL.UWBucket()[pri:10, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UWBucket -->
        <test-method status="SKIP" signature="applicationTracker()[pri:11, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="applicationTracker" duration-ms="0" started-at="2018-09-23T16:56:00Z" depends-on-methods="Cosmos_Testcases.LACosmosToIL.UWBucket" finished-at="2018-09-23T16:56:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LACosmosToIL.applicationTracker()[pri:11, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LACosmosToIL.applicationTracker()[pri:11, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- applicationTracker -->
        <test-method status="SKIP" signature="proposalEnquiry()[pri:12, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="proposalEnquiry" duration-ms="0" started-at="2018-09-23T16:56:00Z" depends-on-methods="Cosmos_Testcases.LACosmosToIL.applicationTracker" finished-at="2018-09-23T16:56:00Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LACosmosToIL.proposalEnquiry()[pri:12, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LACosmosToIL.proposalEnquiry()[pri:12, instance:Cosmos_Testcases.LACosmosToIL@563172d3] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- proposalEnquiry -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:Cosmos_Testcases.LACosmosToIL@563172d3]" name="aftermethod" is-config="true" duration-ms="741" started-at="2018-09-23T16:56:00Z" finished-at="2018-09-23T16:56:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
      </class> <!-- Cosmos_Testcases.LACosmosToIL -->
    </test> <!-- TestLATOIL -->
  </suite> <!-- Suite -->
</testng-results>
